screen_width: 1366
screen_height: 768
info_stock: "This is information about stocks"
info_loan: "This is information about loans"
about_section: "this is a scenario-based learning tool made by 3 awesome students :)"
