requirements:
  develop:
    - pytest=7.1.1
    - flake8=4.0.1
    - isort=5.9.3
    - black=19.10b0

  run:
    - matplotlib=3.5.1
  
  channel:
    - conda-forge autoflake=1.4

  pip:
    - pygame=2.1.2
    - pygame_gui=0.6.4

  

    
    



